### ISSUE TITLE
[ Webmail ] Notice: Undefined property: stdClass::$last_sync_time

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#114]
**Url:**
http://libremail/thread/9/142#

**Stack trace:**
Last sync:
```
Notice: Undefined property: stdClass::$last_sync_time in /var/www/libremail/webmail/views/messages/footer.phtml on line 17

Fatal error: Uncaught TypeError: Argument 1 passed to App\View::timeSpan() must be of the type integer, null given, called in /var/www/libremail/webmail/views/messages/footer.phtml on line 17 and defined in /var/www/libremail/webmail/src/View.php:220 Stack trace: #0 /var/www/libremail/webmail/views/messages/footer.phtml(17): App\View->timeSpan(NULL) #1 /var/www/libremail/webmail/src/View.php(83): include('/var/www/librem...') #2 /var/www/libremail/webmail/views/thread.phtml(48): App\View->render(Object(App\View), Array) #3 /var/www/libremail/webmail/src/View.php(83): include('/var/www/librem...') #4 /var/www/libremail/webmail/src/Controller.php(508): App\View->render(Object(App\View), Array) #5 /var/www/libremail/webmail/src/Controller.php(130): App\Controller->page('thread', Array) #6 [internal function]: App\Controller->thread(9, 142) #7 /var/www/libremail/webmail/src/Router.php(340): call_user_func_array(Array, Array) #8 /var/www/libremail/webmail/src/Router.php(234): App\Router->handle(Array, true) #9 /var/www/librema in /var/www/libremail/webmail/src/View.php on line 220
```

**Screenshot**

![Thread-error](https://user-images.githubusercontent.com/313477/76735531-1dae8580-6776-11ea-9ba8-5622c5021661.PNG)

**Comment by mikegioia** [comment]
@netandreus I'm closing this out but only because I'm actively working on the webmail :D If you don't mind, I would just ask that you please email me before submitting any webmail errors. I may have already fixed them in the other branch.

**Comment by netandreus** [comment]
Ok, @mikegioia , I will write you to email
